### ISSUE TITLE
Special use domains are not supported

### ISSUE THREAD

**Issue by Ambrevar** [lu4nx/cl-tld#2]
Most special use domains are not supported.
See https://en.wikipedia.org/wiki/Special-use_domain_name#cite_note-2.

The notable exception is `.onion` :)
Mind adding the following?
- local
- localhost
- test
- example
- invalid

**Comment by lu4nx** [comment]
@Ambrevar Thanks report, please pull latest code, I add `add-domain-name` function, you can use the following code to add custom domain name:

```
(dolist (domain '("local" "localhost" "test" "example" "invalid"))
  (cl-tld:add-domain-name domain))
```

tests:

```
CL-USER> (cl-tld:get-tld "a.local")
"local"
CL-USER> (cl-tld:get-tld "a.example")
"example"
```

**Comment by Ambrevar** [comment]
Thanks!

Considering these are standard TLDs, shouldn't we make it the default though?

**Comment by lu4nx** [comment]
Hi, because cl-tld depend https://github.com/publicsuffix/list, adding new domains may conflict with them, so I recommend temporarily using the `add-domain-name` function to deal with this bug.

You can refer to:
- https://github.com/publicsuffix/list/pull/1515
- https://github.com/publicsuffix/list/issues/1466

**Comment by Ambrevar** [comment]
Fair enough, thanks!
